define_cvar BHOP, bhop, 1
define_cvar BHOP_STANDUP, bhop_standup, 0
define_cvar BHOP_STANDUP, bhop_standup_fallingspeed, 0

define_cvar ALWAYS_ENABLED, speed, 1000

define_cvar STRAFE, strafe_forwardmove, 35851
define_cvar STRAFE, strafe_sidemove, 10000
define_cvar STRAFE, strafe_use_fps_boost, 1
define_cvar STRAFE & FPS_HELPER, strafe_use_fps_helper, 0

define_cvar GROUND_STRAFE, groundstrafe_nsd, 1
define_cvar GROUND_STRAFE_STANDUP, groundstrafe_standup, 0.001

define_cvar FASTRUN, fastrun_forwardmove, 267.876434
define_cvar FASTRUN, fastrun_sidemove, 135.063748

define_cvar ALWAYS_ENABLED, r_norefresh, 0

define_cvar ALWAYS_ENABLED, fps_boost_skip_nframes, 7
define_cvar ALWAYS_ENABLED, fps_boost_use_config, 1

define_cvar FPS_HELPER, fps_helper, 0

define_cvar ESP_ENABLED, esp, 1
define_cvar ESP_ENABLED, esp_players, 1
define_cvar ESP_ENABLED, esp_entities, 1
