define_cvar bhop, 1
define_cvar bhop_standup, 0
define_cvar bhop_standup_fallingspeed, 0

define_cvar speed, 1000

define_cvar strafe_forwardmove, 35851
define_cvar strafe_sidemove, 10000
define_cvar strafe_use_fps_boost, 1

define_cvar groundstrafe_nsd, 1
define_cvar groundstrafe_standup, 0.001

define_cvar fastrun_forwardmove, 267.876434
define_cvar fastrun_sidemove, 135.063748

define_cvar r_norefresh, 0

define_cvar fps_boost_skip_nframes, 7
